### ISSUE TITLE
能否在弄一个支付宝小程序版本的呢？

### ISSUE THREAD

**Issue by 79229788** [cytle/socket.io-wxapp-client#2]
如题，支付宝小程序已经公测阶段了，看了接口和微信非常相似，因此希望能否提供一个支付宝版本的，非常感谢

**Comment by cytle** [comment]
啊哈哈，可以的，这几天搞下

**Comment by 79229788** [comment]
哈，那先感谢了哈，幸好支付宝和微信的接口基本如出一辙，命名都抄的那么一样，一点都不谦逊，不过对于开发者的我们就是好事。

[另外微信的websocket的事件全都只有on，没看到有off，支付宝却两则都有提供，希望不影响你那边对socket.io的改造哈，确实对socket.io爱不释手，有room的概念，用起来很方便]

附上链接： [https://docs.alipay.com/mini/api/network](https://docs.alipay.com/mini/api/network) 这个页面底部

**Comment by cytle** [comment]
已经增加支付宝小程序打包，参考`readme`使用

**Comment by 79229788** [comment]
好的万分感谢！！！！！

**Comment by 79229788** [comment]
hi, 是不是有个BUG呢，我这边做的业务是，
1.在app文件中new一个全局的io实例
2.进了(onShow方法中)指定页面就用该实例调用connect()，
3.隐藏或卸载页面就调用disconnect()。

那么然后第一轮是没有问题的，就是首次进去后，成功链接上了，出页面后，成功断开，一切正常。

但再一次进入这个页面时connect()已经无效了。没有报错，什么都没有发生。也断点看了，确实执行了 connect()，就是无任何反应

**该业务在微信小程序中一切正常哦(代码也是共用的)**

**Comment by cytle** [comment]
感谢反馈，正在排查问题

**Comment by 79229788** [comment]
重新进页面时connect_error监听到的是连接超时错误
而发现推送到真机上时[白名单无误]，首次连接都直接是连接超时错误，不知道真机上错误是否也是这个原因呢，还是说支付宝那边的原因

**Comment by 79229788** [comment]
关于真机无法连接，我已经写了一个Demo发给支付宝那边技术看了，而本地这边断开后就不能重连接了，就只有麻烦你看看啦，也不知道是哪的问题

**Comment by cytle** [comment]
微信低版本小程序和支付宝小程序websocket只支持单连接

> 基础库 1.7.0 之前，一个微信小程序同时只能有一个 WebSocket 连接，如果当前已存在一个 WebSocket 连接，会自动关闭该连接，并重新创建一个 WebSocket 连接。基础库版本 1.7.0 及以后，支持存在多个 WebSokcet 连接，每次成功调用 wx.connectSocket 会返回一个新的 SocketTask。

我写的`wxapp-socket`原来对**单连接情况**支持不是很好，在创建第二个`websocket`时消息接收存在问题。现在改为在前一个`websocket`完全关闭后再打开第二个，这也限制了同时只能有一个`socket.io`实例连接上。

1.1.8版本试下，应该没问题了，socket断开再连接时间有点长。另外同一个实例为什么需要在页面切换时候断开再连接？？？

**Comment by 79229788** [comment]
支付宝小程序还是不行哦【还是老样子，就是首次可以连接，一旦主动断开后想重新connect()就返回超时错误了】而且控制台还直接打印出
websocket设置全局事件接受者 function (t, e) {
      "close" === t ? n.readyState = r.CLOSED : "open" === t && (n.readyState = r.OPEN), n["on" + t] && n["on" + t](e);
    }

**Comment by cytle** [comment]
```js
```
```js
my.offSocketOpen // undefined ? 这接口。。
```

**Comment by 79229788** [comment]
我这边调用my.offSocketOpen时，打印出ide暂不支持该接口- -，要不先不考虑这些off接口？我看微信就没有提供这些off接口的嘛

**Comment by 79229788** [comment]
而且我也试了，就算不off，每次都重复创建一个on，都不会叠加执行，他内部应该是处理了，那么这个off并没有太多用哈，所以微信就没有提供出来

**Comment by cytle** [comment]
不仅是接口为定义，他们的回调和onSocket**都有问题，报给官方了

https://openclub.alipay.com/read.php?tid=5167&fid=65

我原本一直认为onSocket**这类绑定一次就好，同时也认为绑定多次就会被执行多次。
然而支付宝实现是一个全局websocket实例，执行一次覆盖一次on**属性。

```js
```

**Comment by cytle** [comment]
通过这样可以直接拿到socket实例。哈哈，可以突破只能单个socket限制了。

```js
my.onSocketOpen(function (res) {
    console.log('onSocketOpen this', this); // WebSocket {url: "ws://localhost:8863/socket.io/?id...
});
```

**Comment by 79229788** [comment]
这个官方未来很好修复哈，最好还是不要碰为好，否则一旦用了以后失效更惨哈，唉，现在只想把最基础流程走通先😔

**Comment by cytle** [comment]
版本`v1.1.12`支付宝小程序试下，这下肯定没问题i了

**Comment by 79229788** [comment]
确实可以了，太感谢了，现在就只有真机没法连接了，这个肯定是支付宝那边的问题，到时我在多反馈下试试吧

**Comment by 79229788** [comment]
hi哥们，支付宝官方那边正在解决真机无法连接的问题，他在问我这个库的源码，但只有压缩的，然后他说他先探究下这个压缩后的代码，要不这样，官方为了解决这个问题临时弄了个钉钉websocet的群，只有几个人，全是他们技术，要不你也加进来，如果可以的话，希望留下你的钉钉号哈

**Comment by cytle** [comment]
好哈，钉号： bigbox

**Comment by 79229788** [comment]
好的。他们问了我很多为什么要自己包一个socket.IO我也答不上来哈，你到时可以看聊天记录，毕竟你对这个非常了解，所以只有请你帮忙啦~

**Comment by sjkmuninj** [comment]
支付宝首次连接成功断开后无法重连的这个问题怎么解决?我这边还是有这个问题
